In [1]:
#Import Numpy
import numpy as np


In [5]:
mylist = [1,2,3,4]
mynparray = np.array(mylist)
print(mynparray)
print(type(mynparray))

[1 2 3 4]
<class 'numpy.ndarray'>


In [10]:
#range function
myList2 = list(range(10))
print(myList2)

#arange function in numpy
myList3 = np.arange(10)
print(myList3)

myList4 = np.arange(2, 10)
print(myList4)

myList5 = np.arange(2,10,2)
print(myList5)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 4 6 8]


In [11]:
#zeros returns float values
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros(5, dtype="int32")

array([0, 0, 0, 0, 0], dtype=int32)

In [14]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
np.ones((5,5))+4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [20]:
#linspace gives you evenly spaced numbers between the defined numbers
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [21]:
#eye when you want diagonal 1's
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
#rand in numpy returns a uniformly disturbuted values between 0 and 1
print(np.random.rand(5))
print(np.random.rand(5,5))

[0.12514883 0.25721503 0.76319888 0.42632262 0.70710715]
[[0.08754024 0.04775563 0.16434548 0.69147903 0.64960055]
 [0.80113092 0.99550255 0.74343715 0.93605141 0.61603202]
 [0.25877072 0.97368302 0.09386443 0.25370541 0.89592949]
 [0.55464381 0.05011695 0.63210276 0.49660893 0.91000574]
 [0.78848258 0.17526276 0.6681479  0.41025369 0.63903713]]


In [30]:
#randn normal distribution meaning mean =0 and standard deviation = 1

a = np.random.randn(100)
print(a)
b = np.sum(a)/100

print(b)

[-0.3898475  -1.23309597  0.13165884  0.26820325 -0.59966035  0.15735121
  1.06605003 -0.82602375 -0.76768673  0.65965262 -0.06520211 -1.63409564
  0.5758859   0.64627932  0.99441487 -1.19387802 -1.17694142  2.12852876
  1.3519173   1.84756212 -0.30985757 -2.30562075  1.28520852 -0.51449088
  0.09169173  0.7520562   0.17570231  1.4806308   2.08921459 -0.29110653
  0.57214028  1.57330406 -0.24663161 -0.27761138 -0.75337682  0.86013679
  1.04528819  0.77486521  1.17496808  0.47362451 -0.41800573  0.88825192
  2.03560377 -0.13190434  0.77548404 -0.91151515  0.27854783  0.1332478
 -1.39325878 -0.42812875 -0.05206025  1.60920586  0.05285242  0.91660215
 -0.47812072 -0.0937964   0.43282602  0.74274578 -1.46151847 -0.47803398
  0.03204841  0.21621782  0.93210186 -2.43921232  0.25196813 -0.52147762
  0.64130397 -1.96802961  0.47517207  1.55507777 -1.01172874 -1.88820252
  0.04678595 -0.7855787   0.40349366 -0.821045   -0.26241565 -0.25566347
 -0.1137949   0.58614871  0.29649967  0.29711122  0.

In [36]:
#randint
print(np.random.randint(0,6))
print((np.random.randint(0,5,10)))

4
[0 3 3 4 2 2 4 4 2 0]


In [40]:
np.random.seed(42)
np.random.rand(4)


array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [42]:
#shape
randarr = np.random.randint(0,5,10)
print(randarr)

[1 3 4 0 3 1 4 3 0 0]


In [48]:
print(randarr.shape)
arr = randarr.reshape(5,2)
arr2 = randarr.reshape(-1,1)
print(arr.shape)
print(arr2.shape)

(10,)
(5, 2)
(10, 1)


In [50]:
a =np.random.randint(0,20,10)
print(a)
print(np.max(a))

[ 6  8  6 17  3 13 17  8  1 19]
19


In [52]:
#get the max index value
print(np.argmax(a))
print(np.argmin(a))

9
8


In [53]:
a.dtype

dtype('int64')

In [55]:
#indexing
br = np.arange(0,11)

print(br[1])
print(br[1:5])

print(br[:5])
print(br[5:])


1
[1 2 3 4]
[0 1 2 3 4]
[ 5  6  7  8  9 10]
[10]


In [57]:
ar = br/2
print(ar)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [58]:
br**3


array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [60]:
slice_of = br[:5]
slice_of[:] = 99
print(slice_of)

[99 99 99 99 99]


In [61]:
br #is also affecting

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [62]:
arr = br.copy()
arr[:] = 1000

print(arr)
print(br)

[1000 1000 1000 1000 1000 1000 1000 1000 1000 1000 1000]
[99 99 99 99 99  5  6  7  8  9 10]


In [64]:
#Indexing on 2-D array
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3)
print(arr3.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [67]:
print(arr3[1,1])
print(arr3[1][1])

5
5


In [68]:
arr3[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
arr3[:2,1:]

array([[2, 3],
       [5, 6]])

In [70]:
arrre = np.random.randint(0,10,10)

In [72]:
brre = arrre>4
brre

array([ True,  True, False, False, False, False,  True, False, False,
        True])

In [73]:
arrre[brre]

array([6, 7, 7, 5])

In [74]:
arrre[arrre>4]

array([6, 7, 7, 5])

## Numpy operations

In [78]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [84]:
arr = np.array([1000])
print(arr)
np.log(arr)

[1000]


array([6.90775528])

In [83]:
np.log10(arr)

array([3.])

In [85]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr_2d.sum(axis=0))
print(arr_2d.sum(axis=1))

[15 18 21 24]
[10 26 42]


Exercise


In [87]:
#create a np array of 10 zeros

np.zeros(10, dtype="int64")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [88]:
#create a np array of 10 1
np.ones(10, dtype="int64")

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [89]:
#create a np array of 10 5's
np.ones(10, dtype="int64") * 5


array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [92]:
##create a np array of 10 to 50

np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [94]:
##create a np array of 10 to 50 with even numbers
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [96]:
np.array([[0,1,2],[3,4,5],[6,7,8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [97]:
#create a 3 * 3 np array with ones diagonally
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [98]:
#random number between 0 and 1
np.random.rand(1)

array([0.20794166])

In [99]:
#25 random samples with standard deviation of 1
np.random.randn(25)

array([-0.46146572,  0.06665728, -0.17628566,  1.20089277,  0.69839894,
       -0.17162884, -0.90718658,  1.18862573,  0.78553212,  2.65601009,
        0.26348604,  1.64177112,  0.4608163 ,  0.08592347, -1.50995728,
        0.72150246, -0.84341992, -0.51332541, -0.0435368 , -0.27530091,
       -1.56306679, -0.79563099,  0.9305844 ,  0.67776741,  0.69844026])

In [104]:
np.arange(0.01,1.01,0.01)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [105]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [109]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [110]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [112]:
mat[3,4]

20

In [116]:
mat[:,1].reshape(-1,1)

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

In [117]:
mat[-1,:]

array([21, 22, 23, 24, 25])