In [1]:
import numpy as np
import pandas as pd
import torch

In [2]:
narray = np.array([1,2,3,4,5,6])
ntorch = torch.from_numpy(narray)
print(ntorch)

tensor([1, 2, 3, 4, 5, 6])


In [7]:
torch.zeros(4,3, dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [8]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [11]:
t = torch.arange(0,12,2)
t.reshape(2,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10]])

In [12]:
torch.linspace(0,5,12)

tensor([0.0000, 0.4545, 0.9091, 1.3636, 1.8182, 2.2727, 2.7273, 3.1818, 3.6364,
        4.0909, 4.5455, 5.0000])

In [15]:
mytensor = torch.tensor([1,2,3,4,5,6])
print(mytensor.dtype)
mytensor = mytensor.type(torch.int32)
print(mytensor.dtype)

torch.int64
torch.int32


In [16]:
torch.rand(4,3)

tensor([[0.0409, 0.0720, 0.3306],
        [0.5571, 0.8041, 0.8914],
        [0.6898, 0.8970, 0.0435],
        [0.5756, 0.9773, 0.4728]])

In [17]:
torch.randn(4,3)

tensor([[-0.5912, -0.6221,  0.5694],
        [ 2.4860, -0.0588,  0.5348],
        [-0.4321,  1.4825, -1.3076],
        [-0.7478, -1.0067,  0.0139]])

In [19]:
torch.randint(0,5,(5,5))

tensor([[2, 4, 3, 3, 1],
        [2, 1, 3, 3, 3],
        [0, 4, 4, 0, 3],
        [0, 4, 0, 2, 1],
        [2, 1, 1, 1, 1]])

In [20]:
x = torch.zeros(3,2)

In [21]:
torch.rand_like(x)

tensor([[0.8730, 0.9625],
        [0.6910, 0.9955],
        [0.9834, 0.4897]])

In [22]:
torch.randint_like(x, low=0,high=10)

tensor([[3., 3.],
        [7., 4.],
        [1., 7.]])

In [23]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])